name: "ryoji_wh_demos"
version: "1.0.0"
profile: "ryoji_wh_bigquery"

models:
  ryoji_wh_demos:
    +materialized: view
    staging:
      +schema: staging
      +tags: ["staging"]
    marts:
      core:
        +schema: core
        +tags: ["mart"]
